MyBoard/Board/Ads/urls.py
from django.urls import path
from .views import *
from django.views.decorators.cache import cache_page

urlpatterns = [
    path('', cache_page(60)(PostsList.as_view()), name='posts_list'),
    path('<int:pk>/', cache_page(60*3)(PostDetail.as_view()), name='post'),
    path('post/create/', PostCreate.as_view(), name='post_create'),
    path('post/<int:pk>/update/', PostUpdate.as_view(), name='post_update'),
    path('category/<int:category_pk>/', cache_page(60*3)(CategoryList.as_view()), name='category_list'),
    path('personal/', Personal.as_view(), name='personal'),
    path('accept_response/<int:response_id>/', accept_response, name='accept_response'),
    path('deny_response/<int:response_id>/', deny_response, name='deny_response'),
    path('confirm/', ConfirmUser.as_view(), name='confirm_user'),
    path('posts/category/<int:pk>/subscribe/', subscribe, name='subscribe'),
]

MyBoard/Board/Board/urls.py
from django.contrib import admin
from django.urls import path, include
from Ads.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('posts/', include('Ads.urls')),
    path('sign/', include('sign.urls')),
    path('accounts/', include('allauth.urls')),
    path('', IndexView.as_view()),
]

MyBoard/Board/Ads/models.py
from django.contrib.auth.models import User, AbstractUser
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.

class User(AbstractUser):
    code = models.CharField(max_length=15, blank=True, null=True)


class Category(models.Model):
    dd = 'DD'
    tank = 'TANK'
    heal = 'HEAL'
    td = 'TREADER'
    gm = 'GUILDMASTER'
    qg = 'QUESTGIVER'
    bs = 'BLACKSMITH'
    tn = 'TANNER'
    pn = 'POTIONEER'
    sm = 'SPELLMASTER'

    CATEGORY_TYPES = [
        (dd, 'ДД'),
        (tank, 'Танк'),
        (heal, 'Хил'),
        (td, 'Торговец'),
        (gm, 'Гилдмастер'),
        (qg, 'Квестгивер'),
        (bs, 'Кузнец'),
        (tn, 'Кожевник'),
        (pn, 'Зельевар'),
        (sm, 'Мастер заклинаний')
    ]

    name = models.CharField(max_length=11, choices=CATEGORY_TYPES, default=dd)
    subscribers = models.ManyToManyField(User, blank=True, null=True, related_name='categories')

    def __str__(self):
        return dict(Category.CATEGORY_TYPES)[self.name]


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    text = RichTextUploadingField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=Category.dd)
    date_in = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Response(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField()
    date_in = models.DateTimeField(auto_now_add=True)
    # false - отклик не принят
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.text

MyBoard/Board/templates/accept_response_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>
</head>
<body>
    <h2>Здравствуйте! Ваш отклик к <a href="{{ link }}">посту</a> был принят!</h2>
</body>
</html>

MyBoard/Board/templates/category_list.html
{% extends 'flatpages/default.html' %}
{% block title %}
<h1 class="page-title">Все объявления категории {{ category_name }}</h1>
{% endblock %}
{% block content %}
{% if is_not_subscriber %}
<p class="text-center"><a href="{% url 'subscribe' category.pk %}" class="btn btn-secondary btn-sm">Подписаться</a></p>
{% endif %}
    {% for p in category_posts_list %}
        <div style="border: 2px solid #ccc; border-radius: 10px; padding: 15px; margin-bottom: 20px; background-color: #f8f9fa;">
            <p>{{ p.user }} {{ p.date_in|date:"d E Y, H:i" }}</p>
            <h4><a href="{% url 'post' p.pk %}" style="text-decoration: none; color: black;">{{ p.title }}</a></h4>
            <p style="font-size: 18px; color: gray;">Категория: {{ p.category }}</p>
            <span style="font-size: 22px;">{{ p.text|safe }}</span>
            <p><i><a href="{% url 'post' p.pk %}" style="text-decoration: none; color: black;">Откликнуться 💬 ️️</a></i></p>
        </div>
    {% endfor %}
<div style="text-align: center;">
    {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
</div>
{% endblock %}

MyBoard/Board/templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>
</head>
<body>
    <h2>Здравствуйте! Новые объявления за последнюю неделю</h2>
    <ul>
        {% for post in posts %}
        <li><a href="{{ link }}{{ post.get_absolute_url }}">{{ post.title }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

MyBoard/Board/templates/index.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h2>{{request.user.username}}
<br>
Добро пожаловать на доску объявлений MMORPG!</h2>
<br>
<a href="http://127.0.0.1:8000/posts/" style="padding-left: 50px"> Перейти к просмотру объявлений</a>
<button style="margin-left: 50px">
    {% if not user.is_authenticated %}
        <a class="nav-link" href="http://127.0.0.1:8000/accounts/login/"> Авторизоваться/Зарегистрироваться</a>
    {% else %}
        <a class="nav-link" href="http://127.0.0.1:8000/accounts/logout/"> Выйти</a>
    {% endif %}
</button>

{% endblock %}

MyBoard/Board/templates/login.html
{% extends 'flatpages/default.html' %}

{% block content %}
<div style="text-align: center;">
    <h2>Войти</h2>
    <br>
    <form method="post" action="{% url 'login' %}">
        {% csrf_token %}
        <table style="margin: 0 auto;">
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
        </table>
        <br>
        <input type="submit" value="Войти">
    </form>
    <button> <a href="{% url 'account_signup' %}"> Регистрация </a></button>
</div>
{% endblock %}

MyBoard/Board/templates/logout.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h3 style="padding-left: 20px"> Вы вышли из системы!</h3>
<hr>
<a style="padding-left: 20px" href="http://127.0.0.1:8000/posts/">Перейти к просмотру постов</a>
<br>
<button style="margin-left: 20px">
    <a  class="nav-link" href="http://127.0.0.1:8000/accounts/login/">Войти</a>
</button>
{% endblock %}

MyBoard/Board/templates/logout_confirm.html
{% extends "flatpages/default.html" %}

{% block content %}
<div style="text-align: center;">
    <h2> Вы действительно хотите выйти из системы? </h2>
    <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
            <input type="submit" value="Подтвердить">
    </form>
</div>
{% endblock %}

MyBoard/Board/templates/personal.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Личный кабинет {{ user.username }}</h1>
<hr>
<h4>Выберите объявление</h4>
<br>
<form action="" method="get">
    {{ filterset.form }}
    <br>
    <input type="submit" value="Найти">
</form>
<br>
<button><a href="http://127.0.0.1:8000/posts/personal" style="color: inherit; text-decoration: none;">Сбросить фильтр</a></button>
<br>
<br>
<h4>Отлики на ваши объявления</h4>
{% for r in filterset.qs %}
    {% if not r.status %}
        <div style="border: 1px solid #ccc; border-radius: 10px; padding: 10px; margin-bottom: 10px;">
            <p>{{ r.user }} <a href="{% url 'post' r.post.pk %}" style="color: grey; text-decoration: none;"> {{ r.date_in|date:"d E Y, H:i" }}</a></p>
            <p>{{ r.text }}</p>
            <form action="{% url 'accept_response' r.pk %}" method="post">
                {% csrf_token %}
                <button type="submit">✓ Принять</button>
            </form>
            <form action="{% url 'deny_response' r.pk %}" method="post">
                {% csrf_token %}
                <button type="submit">✘ Отклонить</button>
            </form>
        </div>
    {% endif %}
{% endfor %}

<h4>Принятые отклики</h4>
{% for r in filterset.qs %}
    {% if r.status %}
        <div style="border: 1px solid #ccc; border-radius: 10px; padding: 10px; margin-bottom: 10px;">
            <p>{{ r.user }} <a href="{% url 'post' r.post.pk %}" style="color: grey; text-decoration: none;"> {{ r.date_in|date:"d E Y, H:i" }}</a></p>
            <p>{{ r.text }}</p>
            <button type="button" disabled>✓ Принят</button>
        </div>
    {% endif %}
{% endfor %}

{% endblock %}

MyBoard/Board/templates/post.html
{% extends 'flatpages/default.html' %}
{% block title %}
<h1>{{ post.title }}</h1>
<div style="margin-bottom: 5px; font-size: 18px;">{{ post.user }} {{ post.date_in|date:"d E Y, H:i" }}</div>
<hr>
{% endblock %}
{% block content %}
<div style="text-align: right;">
    {% if user.is_authenticated and user == post.user %}
        <a href="{% url 'post_update' post.pk %}" class="btn btn-primary">Редактировать</a>
    {% endif %}
</div>
<div style="text-align: center; font-size: 30px;">
    {{ post.text|safe }}
</div>
<br>
<form method="post" style="max-width: 1200px; margin: 0 auto;">
    {% csrf_token %}
    <div style="margin-bottom: 10px;">
        {{ response_form.text }}
    </div>
    <button type="submit" class="btn btn-primary">Отправить отклик</button>
</form>
<br>
<h2>Отклики:</h2>
{% if post.response_set.all %}
    <ul>
        {% for response in post.response_set.all %}
            {% if user == post.user or user == response.user %}
                <div style="border: 1px solid #ccc; border-radius: 10px; padding: 10px; margin-bottom: 10px; margin-right: 100px;">
                    <div style="font-weight: bold; margin-bottom: 5px;">{{ response.user }} <span style="color: gray;">{{ response.date_in|date:"d E Y, H:i" }}</span></div>
                    <div style="margin-bottom: 5px;">{{ response.text }}</div>
                </div>
            {% endif %}
            {% if user != post.user or user != response.user %}
                {% if response.status %}
                    <div style="border: 1px solid #ccc; border-radius: 10px; padding: 10px; margin-bottom: 10px; margin-right: 100px;">
                        <div style="font-weight: bold; margin-bottom: 5px;">{{ response.user }} <span style="color: gray;">{{ response.date_in|date:"d E Y, H:i" }}</span></div>
                        <div style="margin-bottom: 5px;">{{ response.text }}</div>
                    </div>
                {% endif %}
            {% endif %}
        {% endfor %}
    </ul>
{% endif %}
{% endblock %}

MyBoard/Board/templates/post_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 text-center">
            <h1>Добавить объявление</h1>
            <hr>
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                {{ form.media }}
                <input type="submit" class="btn btn-primary" value="Save" />
            </form>
        </div>
    </div>
</div>
{% endblock %}

MyBoard/Board/templates/posts_list.html
{% extends 'flatpages/default.html' %}
{% block title %}
<h1 class="page-title">Все объявления:</h1>
{% endblock %}
{% block content %}
    {% for p in posts %}
        <div style="border: 2px solid #ccc; border-radius: 10px; padding: 15px; margin-bottom: 20px; background-color: #f8f9fa;">
            <p>{{ p.user }} {{ p.date_in|date:"d E Y, H:i" }}</p>
            <h4><a href="{% url 'post' p.pk %}" style="text-decoration: none; color: black;">{{ p.title }}</a></h4>
            <a href="{% url 'category_list' category_pk=p.category.pk %}" style="color: inherit; text-decoration: none;">
                <p style="font-size: 18px; color: gray;">Категория: {{ p.category }}</p>
            </a>
            <span style="font-size: 22px;">{{ p.text|safe }}</span>
            <p><i><a href="{% url 'post' p.pk %}" style="text-decoration: none; color: black;">Откликнуться 💬 ️️</a></i></p>
        </div>
    {% endfor %}

<div style="text-align: center;">
    {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
</div>
{% endblock %}

MyBoard/Board/templates/profile.html
{% extends 'flatpages/default.html' %}
{% block content %}
<h1>Личный кабинет {{ user.username }}</h1>
<button><a href="{% url 'logout' %}">Выйти</a> </button>
{% endblock content %}

MyBoard/Board/templates/response_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>
</head>
<body>
    <h2>Здравствуйте! Новый отклик на ваш <a href="{{ link }}">пост</a>!</h2>
    <p>{{ author }}</p>
    <p>{{ text }}</p>
</body>
</html>

MyBoard/Board/templates/subscribe_success.html
{% extends 'flatpages/default.html' %}
{% block content %}
<h1 class="text-center">Вы успешно подписались</h1>
{% endblock %}